version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitProjectTest4Project
  gitServerName: https://github.com/
  gitUrl: https://github.com/y509522/ExternalTargetProject
  gitUsername: y509522
  gitBranch: main
